### ISSUE TITLE
Console Error: Avoid mutating a prop directly and ReferenceError: payload is not defined

### ISSUE THREAD

**Issue by fahad-larasoft** [nemrutco/nova-filterable-metrics#10]
I've included your "nemrutco/nova-filterable-metrics": "^1.1" in my Laravel 5.8 and Laravel Nova 2.0 project. But getting errors in console:

- When I open the filter daterangepicker modal: `[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "placeholder"`

- and when I select a date range from daterangepicker: `[Vue warn]: Error in v-on handler: "ReferenceError: payload is not defined" `

See screenshots below for details:

<img width="1431" alt="Screenshot 2020-05-18 at 3 59 17 PM" src="https://user-images.githubusercontent.com/7126820/82206098-07ad7480-9921-11ea-83ee-aa087ea08486.png">

<img width="1434" alt="Screenshot 2020-05-18 at 3 59 37 PM" src="https://user-images.githubusercontent.com/7126820/82206109-0d0abf00-9921-11ea-8daf-86cb679a81db.png">

**Comment by ibrahem-kamal** [comment]
same issue here

**Comment by nukunet** [comment]
I got the same error

**Comment by nukunet** [comment]
I found a solution

Metrics file 
App\Nova\Metrics
`public function uriKey()
    {
        return 'ooo-xxx';
    }`

Filters file
App\Nova\Filters
`protected function componentName()
    {
        return 'ooo-xxx';
    }`

Set to the same, which is not stated in the file

**Comment by Aylarius** [comment]
I have the same issue... Filters no longer work on metrics (Nova 2.0, Laravel 5.8) and the only error I get is `ReferenceError: payload is not defined`
I tried with all releases (1.1.1, 1.1.0 and 1.0.0)

**Comment by Aylarius** [comment]
Actually the release `1.0.0` seems to be working fine with Nova `2.12.0`

**Comment by muzafferdede** [comment]
Sorry, didn't have time to catch up with this issue. Is this fixed by v1.1.2 release ?

**Comment by chilio** [comment]
@muzafferdede release fixes error but unfortunately, metrics are not updated according to the selected date in my case.
After date selection, toast Filtered Date is shown, but no xhr request is being made.
That's sad because I find your plugin very useful.
I am using:
PHP 7.4.5
Laravel 7.22.4
Nova 3.8.2

**Comment by muzafferdede** [comment]
@chilio Thanks for the helpful info. should be fixed by v1.1.3.

**Comment by chilio** [comment]
@muzafferdede I've just tried new release v1.1.3.
Console produces no errors, but requested date or date range is not applied.
Now XHR request is actually made, but with no additional (date) parameters, just simple route via GET.

**Comment by muzafferdede** [comment]
@chilio revised v1.1.3, didn't want to make new release and i don't have proper environment to do the tests but i think it's fine now. Make sure clear copmposer cache to receive new v1.1.3 since you already cached it.

**Comment by chilio** [comment]
@muzafferdede I've executed all composer commands you mentioned. 
Restarted web server.
Unfortunately, the problem still persists :(
I still see that XHR request is being made without additional parameters.

**Comment by muzafferdede** [comment]
@chilio i think it i because cache, anyways i make new release tag v1.1.4. To confirm you are on latest please check last commit and see if have [these](https://github.com/nemrutco/nova-filterable-metrics/commit/ca8fbf2850b75b27dfb3c3898a5db281c1022991#diff-ad7c4aef2e8272e5b930221260427fe8R55) changes.

**Comment by chilio** [comment]
@muzafferdede I've updated to v1.1.4 and we are going further a bit.

**Comment by muzafferdede** [comment]
Date filter gives you a string. you can't call startOfDay() on string.

**Comment by chilio** [comment]
@muzafferdede ok I'll try to cast vars that way...

**Comment by muzafferdede** [comment]
Closing this issue for now. Let me know if there is any issues with the applied fix.
